# Generated by Django 3.1.2 on 2022-03-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='予約日')),
                ('time', models.DateTimeField(verbose_name='予約時間')),
            ],
            options={
                'verbose_name_plural': '予約一覧',
                'db_table': 'reserves',
            },
        ),
    ]
